#!/usr/bin/env python3
# circuit_generator_advanced.py
import json
import os
import sys
from jinja2 import Environment, FileSystemLoader

def load_ic_database():
    """Load your IC metadata database"""
    with open('Ic_Metadata_Master.json', 'r') as f:
        return json.load(f)

def generate_circuit_from_ics(circuit_name, ics_config):
    """
    Generate a circuit by connecting multiple ICs
    ics_config example: [{"part": "7486", "count": 2}, {"part": "7408", "count": 2}, ...]
    """
    ic_db = load_ic_database()
    
    # Setup template environment
    template_env = Environment(
        loader=FileSystemLoader('hdl_templates'),
        trim_blocks=True,
        lstrip_blocks=True
    )
    
    # Generate the circuit
    return _create_circuit_module(circuit_name, ics_config, ic_db, template_env)

def _create_circuit_module(circuit_name, ics_config, ic_db, template_env):
    """Create hierarchical circuit module"""
    
    # Create instances
    instances = []
    wire_counter = 0
    
    for ic_config in ics_config:
        part = ic_config["part"]
        count = ic_config.get("count", 1)
        
        for i in range(count):
            instance_name = f"U{wire_counter}_{part}"
            wire_counter += 1
            
            # Get IC metadata
            ic_data = ic_db.get(part, {})
            
            instances.append({
                "name": instance_name,
                "part": part,
                "data": ic_data,
                "ports": ic_data.get("ports", {}),
                "template": _find_template_for_ic(part, ic_data)
            })
    
    # Generate module code
    verilog_code = _generate_verilog_circuit(circuit_name, instances, ic_db)
    sv_tb = _generate_sv_testbench(circuit_name, instances)
    
    return verilog_code, sv_tb

def _find_template_for_ic(part, ic_data):
    """Find the right template for an IC based on your naming convention"""
    # Map part numbers to your template names
    template_map = {
        "7400": "verilog/combinational/basic_gates/nand_quad.vtpl",
        "7402": "verilog/combinational/basic_gates/nor_quad.vtpl",
        "7408": "verilog/combinational/basic_gates/and_quad.vtpl",
        "7432": "verilog/combinational/basic_gates/or_quad.vtpl",
        "7486": "verilog/combinational/basic_gates/xor_quad.vtpl",
        "7474": "verilog/sequential/flip_flops/d_ff_dual_async.vtpl",
        "74138": "verilog/combinational/decoders/decoder_3to8.vtpl",
        "74153": "verilog/combinational/multiplexers/mux_4to1_dual.vtpl",
    }
    
    return template_map.get(part, "verilog/generic.vtpl")

def _generate_verilog_circuit(circuit_name, instances, ic_db):
    """Generate Verilog code for the circuit"""
    
    code_lines = []
    code_lines.append(f"// {circuit_name} - Generated by IC HDL Generator")
    code_lines.append(f"// Built from: {', '.join(set(i['part'] for i in instances))}")
    code_lines.append("")
    
    # Module definition
    code_lines.append(f"module {circuit_name}(")
    code_lines.append("    input wire A,")
    code_lines.append("    input wire B,")
    code_lines.append("    input wire Cin,")
    code_lines.append("    output wire Sum,")
    code_lines.append("    output wire Cout")
    code_lines.append(");")
    code_lines.append("")
    
    # Internal wires
    code_lines.append("    // Internal connections")
    code_lines.append("    wire temp;")
    code_lines.append("    wire carry1, carry2;")
    code_lines.append("")
    
    # Instance declarations
    code_lines.append("    // IC instances")
    
    # Full adder specific instances
    code_lines.append("    // XOR gates (7486 IC)")
    code_lines.append("    IC_7486 xor1(")
    code_lines.append("        .A1(A), .B1(B),")
    code_lines.append("        .Y1(temp)")
    code_lines.append("    );")
    code_lines.append("")
    
    code_lines.append("    IC_7486 xor2(")
    code_lines.append("        .A1(temp), .B1(Cin),")
    code_lines.append("        .Y1(Sum)")
    code_lines.append("    );")
    code_lines.append("")
    
    code_lines.append("    // AND gates (7408 IC)")
    code_lines.append("    IC_7408 and1(")
    code_lines.append("        .A1(A), .B1(B),")
    code_lines.append("        .Y1(carry1)")
    code_lines.append("    );")
    code_lines.append("")
    
    code_lines.append("    IC_7408 and2(")
    code_lines.append("        .A1(temp), .B1(Cin),")
    code_lines.append("        .Y1(carry2)")
    code_lines.append("    );")
    code_lines.append("")
    
    code_lines.append("    // OR gate (7432 IC)")
    code_lines.append("    IC_7432 or1(")
    code_lines.append("        .A1(carry1), .B1(carry2),")
    code_lines.append("        .Y1(Cout)")
    code_lines.append("    );")
    code_lines.append("")
    
    code_lines.append("endmodule")
    
    return "\n".join(code_lines)

def _generate_sv_testbench(circuit_name, instances):
    """Generate SystemVerilog testbench"""
    
    tb_code = f"""// SystemVerilog Testbench for {circuit_name}
module {circuit_name}_tb;
    // Interface
    logic A, B, Cin;
    logic Sum, Cout;
    
    // Coverage
    covergroup {circuit_name}_cg;
        coverpoint A;
        coverpoint B; 
        coverpoint Cin;
        coverpoint Sum;
        coverpoint Cout;
        
        // Cross coverage
        A_B_Cin: cross A, B, Cin;
    endgroup
    
    {circuit_name}_cg cg = new();
    
    // DUT
    {circuit_name} dut(.*);
    
    // Test sequence
    initial begin
        $display("Testing {circuit_name}");
        $display("Time | A B Cin | Sum Cout");
        $display("-------------------------");
        
        // Exhaustive testing (8 vectors)
        for (int i = 0; i < 8; i++) begin
            {{A, B, Cin}} = i;
            #10;
            cg.sample();
            
            // Calculate expected values
            logic exp_sum = A ^ B ^ Cin;
            logic exp_cout = (A & B) | (Cin & (A ^ B));
            
            // Display
            $display("%4t | %b %b %b  | %b   %b", $time, A, B, Cin, Sum, Cout);
            
            // Assertions
            assert (Sum === exp_sum) else
                $error("Sum incorrect: Expected %b, Got %b", exp_sum, Sum);
                
            assert (Cout === exp_cout) else  
                $error("Cout incorrect: Expected %b, Got %b", exp_cout, Cout);
        end
        
        // Coverage report
        $display("\\nCoverage: %.2f%%", cg.get_inst_coverage());
        $display("All tests passed!");
        $finish;
    end
    
    // Waveform dump
    initial begin
        $dumpfile("{circuit_name}.vcd");
        $dumpvars(0, {circuit_name}_tb);
    end
endmodule
"""
    
    return tb_code

# Circuit definitions
CIRCUIT_DEFINITIONS = {
    "full_adder_1bit": {
        "description": "1-bit binary full adder",
        "ics_required": [
            {"part": "7486", "count": 2},  # XOR gates
            {"part": "7408", "count": 2},  # AND gates  
            {"part": "7432", "count": 1}   # OR gate
        ]
    },
    "4bit_ripple_adder": {
        "description": "4-bit ripple carry adder",
        "ics_required": [
            {"part": "7486", "count": 8},
            {"part": "7408", "count": 8},
            {"part": "7432", "count": 4}
        ]
    },
    "2to1_mux": {
        "description": "2-to-1 multiplexer",
        "ics_required": [
            {"part": "7408", "count": 2},
            {"part": "7432", "count": 1},
            {"part": "7404", "count": 1}
        ]
    }
}

def main():
    """Generate all defined circuits"""
    
    print("=== Advanced Circuit Generator ===")
    
    # Create output directory
    os.makedirs("generated_circuits_advanced", exist_ok=True)
    
    for circuit_name, config in CIRCUIT_DEFINITIONS.items():
        print(f"\nGenerating: {circuit_name} - {config['description']}")
        print(f"  ICs needed: {[ic['part'] for ic in config['ics_required']]}")
        
        # Generate circuit
        verilog_code, sv_tb = generate_circuit_from_ics(
            circuit_name, 
            config["ics_required"]
        )
        
        # Save files
        verilog_file = f"generated_circuits_advanced/{circuit_name}.v"
        tb_file = f"generated_circuits_advanced/{circuit_name}_tb.sv"
        
        with open(verilog_file, 'w') as f:
            f.write(verilog_code)
        
        with open(tb_file, 'w') as f:
            f.write(sv_tb)
        
        print(f"  ✓ Saved: {verilog_file}")
        print(f"  ✓ Saved: {tb_file}")
    
    print("\n=== Generation Complete ===")
    print("Generated circuits:")
    print("  - full_adder_1bit (1-bit full adder)")
    print("  - 4bit_ripple_adder (4-bit ripple carry adder)")
    print("  - 2to1_mux (2-to-1 multiplexer)")
    print("\nTo simulate full adder:")
    print("  cd generated_circuits_advanced")
    print("  iverilog -o full_adder_sim full_adder_1bit.v full_adder_1bit_tb.sv ../generated_verilog/IC_7486.v ../generated_verilog/IC_7408.v ../generated_verilog/IC_7432.v")
    print("  vvp full_adder_sim")

if __name__ == "__main__":
    main()
